---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypetsgreat-deployment
  labels:
    app: mypetsgreat
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mypetsgreat
      tier: frontend
  template:
    metadata:
      labels:
        app: mypetsgreat
        tier: frontend
    spec:
      containers:
      - name: mypetsgreat
        image: gcr.io/doug-rehnstrom/pets-app:401c846
        env:
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "0.5"

---

apiVersion: v1
kind: Service
metadata:
  name: mypetsgreat-deployment-lb
  labels:
    app: mypetsgreat
    tier: frontend-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: mypetsgreat
    tier: frontend
 
---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: mypetsgreat-deployment-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1
    kind: Deployment
    name: mypetsgreat-deployment
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60